### ISSUE TITLE
Response won't show

### ISSUE THREAD

**Issue by andersennl** [djfpaagman/alfredo#1]
I'm working on my first script filter workflow for Alfred and I'm having trouble showing the script's response in Alfred.

This is my Ruby code in my script file:

``` ruby
$:.unshift File.dirname(__FILE__)
require 'alfredo'

workflow = Alfredo::Workflow.new
workflow << Alfredo::Item.new(title: 'mytitle')
workflow.output!
```

Then, in Alfred, I type the name of the workflow, a space, and something random. The only thing I can see then is the standard "search google, wikipedia or amazon" options.

Am I missing something obvious here? As far as I understand, the `Alfredo item` is supposed to appear beneath the Alfred search bar as a result? Thanks!

**Comment by djfpaagman** [comment]
Hi @andersennl,

To be honest I haven't used this gem in a while. It probably has to do with the gem not being installed to the system ruby that Alfred uses. Can you show me the debug log you can get from Alfred?

You can enable it by pressing the bug icon in the workflow editor:

![](http://img.springe.st/1cejaho73y.png)

If you run your command after that some output should appear on the bottom of the editor.

**Comment by andersennl** [comment]
Hi @djfpaagman,
thanks for the fast response and the hint! You're right, here is the debug error message:
```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alfredo (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from start.rb:13:in `<main>'
```
I actually installed alfredo before but where surprised that `which alfredo` says that Alfredo isn't installed.
So I installed it again... please have a look:
```bash
gem install alfredo
Successfully installed alfredo-0.1.2
Parsing documentation for alfredo-0.1.2
Done installing documentation for alfredo after 0 seconds
1 gem installed
➜  user.workflow.933BEE49-372E-47AD-9293-6F120381174C  which alfredo
alfredo not found
```

**Comment by djfpaagman** [comment]
Are you using rbenv or rvm? I think you need to install the gem for the system ruby (`/usr/bin/ruby`) that Alfredo uses.

**Comment by andersennl** [comment]
I'm using rvm. Ok I'll try that, thanks for your help!

**Comment by djfpaagman** [comment]
@andersennl I took some time to create a workflow today, and found a pretty good solution to the gem problem, making workflows portable and not dependent on locally installed gems.

You can see my solution in this workflow: https://github.com/djfpaagman/alfred-provider-suggest.

I might write a short post about this and add it to README for further reference. Closing this issue now, becauseI think we have a nice solution :grin:

**Comment by andersennl** [comment]
Thank you so much @djfpaagman , I'll take a look at it as soon as possible.

**Comment by andersennl** [comment]
@djfpaagman it works! The `require_relative 'vendor/bundle/bundler/setup'` together with the vendor folder was the key. Thank you so much!

**Comment by djfpaagman** [comment]
sweet :tada:
